### ISSUE TITLE
todo

### ISSUE THREAD

**Issue by WHaverals** [WHaverals/stresser#1]
- [x] Alle stresserfunctionaliteit uit stressen verhuizen naar deze repo
- [x] Data naar zendodo (json) @wouter 
- [x] Beschrijven van de taak - klemtoonextractie uit rijmen, regels voor secundaire klemtoontoekenning, manuele correctie die Wouter uitvoerde in de json @wouter
- [x] Code opkuisen @mike
- [x] Memory-based baseline toevoegen @folgert
- [x] Meer en betere evaluatie (Levenstein; syllabificatie en klemtoontoekkening apart)
- [x] Vergelijking van stand-alone syllabificatie en nieuwe syllabificatiemethode op dezelfde testdata
- [ ] Toepassing op de Lutgart @wouter
